SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS Grade;
CREATE TABLE IF NOT EXISTS Grade ( 
	GradeID INT NOT NULL AUTO_INCREMENT,
	Title VARCHAR(128) NOT NULL,
	Code VARCHAR(16) NOT NULL,
	SpineMin INT NOT NULL DEFAULT '1',
	SpineMax INT NOT NULL DEFAULT '1',
	
	PRIMARY KEY (GradeID),
	UNIQUE INDEX GradeID (GradeID ASC),
	UNIQUE INDEX Code (Code ASC))
	ENGINE = InnoDB DEFAULT CHARSET=latin1;
		
DROP TABLE IF EXISTS Skill;
CREATE TABLE IF NOT EXISTS Skill (
	SkillID BIGINT NOT NULL AUTO_INCREMENT,
	Title VARCHAR(255) NOT NULL,
	
	PRIMARY KEY (SkillID),
	UNIQUE INDEX SkillID (SkillID ASC),
	UNIQUE INDEX Title (Title ASC))
	ENGINE = InnoDB DEFAULT CHARSET=latin1;
	
DROP TABLE IF EXISTS Project;
CREATE TABLE IF NOT EXISTS Project (
	ProjectID BIGINT NOT NULL AUTO_INCREMENT,
	Title VARCHAR(255) NOT NULL,
	Notes TEXT DEFAULT NULL,
	Internal BOOLEAN NOT NULL DEFAULT '0',
	`Sensitive` BOOLEAN NOT NULL DEFAULT '0',
	`Started`	DATE NOT NULL,
	`Ended` DATE DEFAULT NULL,
	
	PRIMARY KEY (ProjectID),
	UNIQUE INDEX ProjectID (ProjectID ASC),
	INDEX Title (Title ASC),
	INDEX Notes (Notes(255) ASC))
	ENGINE = InnoDB DEFAULT CHARSET=latin1;
	
DROP TABLE IF EXISTS Equipment;
CREATE TABLE IF NOT EXISTS Equipment (
	EquipmentID BIGINT NOT NULL AUTO_INCREMENT,
	`Type` VARCHAR(255) NOT NULL,
	Make VARCHAR(255) DEFAULT NULL,
	Model VARCHAR(255) DEFAULT NULL,
	Description VARCHAR(255) DEFAULT NULL,
	OperationNotes TEXT DEFAULT NULL,
	Damaged BOOLEAN NOT NULL DEFAULT '0',
	
	PRIMARY KEY (EquipmentID),
	UNIQUE INDEX EquipmentID (EquipmentID ASC),
	INDEX `Type` (`Type` ASC),
	INDEX Model (Model ASC),
	INDEX Description (Description ASC),
	INDEX Damaged (Damaged ASC))
	ENGINE = InnoDB DEFAULT CHARSET=latin1;
	
DROP TABLE IF EXISTS Employee;
CREATE TABLE IF NOT EXISTS Employee (
	EmployeeID BIGINT NOT NULL AUTO_INCREMENT,
	Title VARCHAR(32) DEFAULT NULL,
	FirstName VARCHAR(255) NOT NULL,
	LastName VARCHAR(255) NOT NULL,
	Email VARCHAR(255) DEFAULT NULL,
	Joined DATE DEFAULT NULL,
	`Left` DATE DEFAULT NULL,
	`Current` BOOLEAN NOT NULL DEFAULT '1',
	Phone VARCHAR(32) NOT NULL,
	GradeID INT NOT NULL,
	Manager BIGINT DEFAULT NULL,
	
	PRIMARY KEY (EmployeeID),
	FOREIGN KEY (GradeID) REFERENCES Grade(GradeID) ON DELETE NO ACTION ON UPDATE NO ACTION,
	FOREIGN KEY (Manager) REFERENCES Employee(EmployeeID) ON DELETE NO ACTION ON UPDATE NO ACTION,
	UNIQUE INDEX EmployeeID (EmployeeID ASC),
	INDEX FirstName (FirstName ASC),
	INDEX LastName (LastName ASC),
	UNIQUE INDEX Email (Email ASC),
	INDEX `Current` (`Current` ASC),
	INDEX Manager (Manager ASC))
	ENGINE = InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS FileItem;
CREATE TABLE IF NOT EXISTS FileItem (
	ItemID BIGINT NOT NULL AUTO_INCREMENT,
	Title VARCHAR(255) NOT NULL DEFAULT '',
	Location VARCHAR(255) NOT NULL DEFAULT '',
	EmployeeID BIGINT NOT NULL,
	
	PRIMARY KEY (ItemID),
	FOREIGN KEY (EmployeeID) REFERENCES Employee(EmployeeID) ON DELETE NO ACTION ON UPDATE NO ACTION,
	UNIQUE INDEX ItemID (ItemID ASC),
	INDEX Title (Title ASC),
	INDEX EmployeeID (EmployeeID ASC))
	ENGINE = InnoDB DEFAULT CHARSET=latin1;
	
DROP TABLE IF EXISTS EmployeeSkill;
CREATE TABLE IF NOT EXISTS EmployeeSkill (
	EmployeeID BIGINT NOT NULL,
	SkillID BIGINT NOT NULL,
	DateAchieved DATE DEFAULT NULL,
	
	FOREIGN KEY (EmployeeID) REFERENCES Employee(EmployeeID) ON DELETE NO ACTION ON UPDATE NO ACTION,
	FOREIGN KEY (SkillID) REFERENCES Skill(SkillID) ON DELETE NO ACTION ON UPDATE NO ACTION,
	INDEX EmployeeID (EmployeeID ASC),
	INDEX SkillID (SkillID ASC))
	ENGINE = InnoDB DEFAULT CHARSET=latin1;
	
DROP TABLE IF EXISTS Assignment;
CREATE TABLE IF NOT EXISTS Assignment (
	ProjectID BIGINT NOT NULL,
	EmployeeID BIGINT NOT NULL,
	
	FOREIGN KEY (ProjectID) REFERENCES Project(ProjectID) ON DELETE NO ACTION ON UPDATE NO ACTION,
	FOREIGN KEY (EmployeeID) REFERENCES Employee(EmployeeID) ON DELETE NO ACTION ON UPDATE NO ACTION,
	INDEX ProjectID (ProjectID ASC),
	INDEX EmployeeID (EmployeeID ASC))
	ENGINE = InnoDB DEFAULT CHARSET=latin1;
	
DROP TABLE IF EXISTS Expense;
CREATE TABLE IF NOT EXISTS Expense (
	ExpenseID BIGINT NOT NULL AUTO_INCREMENT,
	EmployeeID BIGINT NOT NULL,
	ProjectID BIGINT DEFAULT NULL,
	Description VARCHAR(255) NOT NULL,
	Amount DOUBLE NOT NULL,
	Paid BOOLEAN NOT NULL DEFAULT '0',
	
	PRIMARY KEY (ExpenseID),
	FOREIGN KEY (EmployeeID) REFERENCES Employee(EmployeeID) ON DELETE NO ACTION ON UPDATE NO ACTION,
	FOREIGN KEY (ProjectID) REFERENCES Project(ProjectID) ON DELETE NO ACTION ON UPDATE NO ACTION,
	UNIQUE INDEX ExpenseID (ExpenseID ASC),
	INDEX EmployeeID (EmployeeID ASC),
	INDEX ProjectID (ProjectID ASC),
	INDEX Description (Description ASC))
	ENGINE = InnoDB DEFAULT CHARSET=latin1;
	
DROP TABLE IF EXISTS Payslip;
CREATE TABLE IF NOT EXISTS Payslip (
	PayslipID BIGINT NOT NULL AUTO_INCREMENT,
	EmployeeID BIGINT NOT NULL,
	Taxable DOUBLE NOT NULL DEFAULT '0',
	NonTaxable DOUBLE NOT NULL DEFAULT '0',
	IncomeTax DOUBLE NOT NULL DEFAULT '0',
	NationalInsurance DOUBLE NOT NULL DEFAULT '0',
	NetPay DOUBLE NOT NULL DEFAULT '0',
	Payday DATE NOT NULL,
	TransferDay DATE NOT NULL,
	TransferRef VARCHAR(32) NOT NULL,
	
	PRIMARY KEY (PayslipID),
	FOREIGN KEY (EmployeeID) REFERENCES Employee(EmployeeID) ON DELETE NO ACTION ON UPDATE NO ACTION,
	UNIQUE INDEX PaysilpID (PayslipID ASC),
	INDEX EmployeeID (EmployeeID ASC))
	ENGINE = InnoDB DEFAULT CHARSET=latin1;
	
DROP TABLE IF EXISTS Contract;
CREATE TABLE IF NOT EXISTS Contract (
	ContractID BIGINT NOT NULL AUTO_INCREMENT,
	Title VARCHAR(255) NOT NULL,
	`Start` DATE NOT NULL,
	DueFinish DATE DEFAULT NULL,
	ActualFinish DATE DEFAULT NULL,
	EmployeeID BIGINT NOT NULL,
	
	PRIMARY KEY (ContractID),
	FOREIGN KEY (EmployeeID) REFERENCES Employee(EmployeeID) ON DELETE NO ACTION ON UPDATE NO ACTION,
	UNIQUE INDEX ContractID (ContractID ASC),
	INDEX Title (Title ASC),
	INDEX EmployeeID (EmployeeID ASC))
	ENGINE = InnoDB DEFAULT CHARSET=latin1;
	
DROP TABLE IF EXISTS EquipmentLoan;
CREATE TABLE IF NOT EXISTS EquipmentLoan (
	EmployeeID BIGINT NOT NULL,
	EquipmentID BIGINT NOT NULL,
	StartDate DATE NOT NULL,
	EndDate DATE DEFAULT NULL,
	`Current` BOOLEAN NOT NULL DEFAULT '1',
	Notes TEXT,
	
	FOREIGN KEY (EmployeeID) REFERENCES Employee(EmployeeID) ON DELETE NO ACTION ON UPDATE NO ACTION,
	FOREIGN KEY (EquipmentID) REFERENCES Equipment(EquipmentID) ON DELETE NO ACTION ON UPDATE NO ACTION,
	INDEX EmployeeID (EmployeeID ASC),
	INDEX EquipmentID (EquipmentID ASC),
	INDEX StartDate (StartDate ASC),
	INDEX EndDate (EndDate AsC),
	INDEX `Current` (`Current` ASC))
	ENGINE = InnoDB DEFAULT CHARSET=latin1;